### ISSUE TITLE
Detecting package cycles in multi-language projects

### ISSUE THREAD

**Issue by Zetten** [wenns/sonar-cxx#325]
In a Maven project which has code in multiple languages, e.g. C++ and Java, the design analysis (as introduced in 797747fcc5a259573b1982e1ce3f9849129c34b0) leads to a duplicate measure error.

This is causing an issue for a JNA module which sits on the boundary between C++ and Java code (using the nar-maven-plugin). In this instance C++ is found in src/main/{c++,include} and Java is just in src/test/java, but it could equally have a src/main/java as well. The package cycle/tangle detection measures are applied at the project level and both Sonar-CXX and Sonar-Java are attempting to add a measure with the same key.

I've worked around it for now by forcing `sonar.language` to `c++` in this module since the Java code is only tests, but that won't be true in all cases.

I'm not entirely sure this is solely a Sonar-CXX issue - in fact I suspect it will affect any given pair of language plugins that try to save the `package_cycles` metric. But I figured I'll start here and move up to the main SQ mailing list if it's definitely an upstream problem.

The exact error:
```
Caused by: org.sonar.api.utils.SonarException: Can not add the same measure twice on org.sonar.api.resources.Project@3697e8c4[id=7,key=com.example:jna-tests,qualifier=BRC]: org.sonar.api.measures.Measure@3a4b5abd[metricKey=package_cycles,metric=Metric[id=124,key=package_cycles,description=Package cycles,type=INT,direction=-1,domain=<null>,name=package_cycles,qualitative=true,userManaged=false,enabled=true,origin=JAV,worstValue=<null>,bestValue=0.0,optimizedBestValue=false,hidden=false,deleteHistoricalData=false],value=0.0,data=<null>,description=<null>,alertStatus=<null>,alertText=<null>,tendency=<null>,date=<null>,variation1=<null>,variation2=<null>,variation3=<null>,variation4=<null>,variation5=<null>,url=<null>,characteristic=<null>,requirement=<null>,personId=<null>,persistenceMode=FULL]
	at org.sonar.batch.index.DefaultIndex.addMeasure(DefaultIndex.java:222)
	at org.sonar.batch.DefaultSensorContext.saveMeasure(DefaultSensorContext.java:173)
	at org.sonar.batch.DefaultSensorContext.saveMeasure(DefaultSensorContext.java:167)
	at org.sonar.plugins.cxx.squid.DependencyAnalyzer.savePositiveMeasure(DependencyAnalyzer.java:263)
	at org.sonar.plugins.cxx.squid.DependencyAnalyzer.save(DependencyAnalyzer.java:164)
...
```

**Comment by wenns** [comment]
The package/file tangle detection implementation in its current form wont exist for too long (see #364.). Until  it vanishes, the probability of this situation is pretty small. Im tempted to just let it alone. The issue can be escalated again if need arizes. @zetten: thanks, it was instructive ;)

**Comment by Zetten** [comment]
Thanks for your help in passing the issue upstream! It's good to know there may be cross-language design metrics in the core architecture soon.

If our projects end up wanting some of the new sonar-cxx features before SQ-5.0/CXX-0.9.3 and we hit the issue again I'll simply deploy a custom version which doesn't try to save these metrics. It looks like it should be fairly straightforward if necessary.
