### ISSUE TITLE
java.nio.charset.MalformedInputException in FileRegularExpressionCheck.java:120

### ISSUE THREAD

**Issue by Bertk** [wenns/sonar-cxx#371]
I activated the FileRegularExpressionCheck for checking includes of stdafx.h in other header files but the analysis fails after some time. Looks like the encoding for the source files (*sonar.sourceEncoding*) is not handled in FileRegularExpressionCheck.java and the exception is not handled as well.
The analysis with sonar_runner fails:
```
ERROR: Error during Sonar runner execution
ERROR: Unable to execute Sonar
ERROR: Caused by: Unable to analyze file: C:\TFS_Server\Server\some-folder\some-header.h
ERROR: Caused by: java.nio.charset.MalformedInputException: Input length = 1
ERROR: Caused by: Input length = 1
``` 
The debug output has the details:
```
org.sonar.runner.impl.RunnerException: Unable to execute Sonar
        at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:91)
        at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69)
        at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50)
        at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:102)
        at org.sonar.runner.api.Runner.execute(Runner.java:100)
        at org.sonar.runner.Main.executeTask(Main.java:70)
        at org.sonar.runner.Main.execute(Main.java:59)
        at org.sonar.runner.Main.main(Main.java:53)
Caused by: org.sonar.squidbridge.api.AnalysisException: Unable to analyze file: C:\TFS_Server\Server\some-folder\some-header.h
        at org.sonar.squidbridge.AstScanner.scanFiles(AstScanner.java:127)
        at org.sonar.plugins.cxx.squid.CxxSquidSensor.analyse(CxxSquidSensor.java:112)
        at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:79)
        at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:70)
        at org.sonar.batch.phases.PhaseExecutor.execute(PhaseExecutor.java:119)
        at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:194)
        at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:92)
        at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:77)
        at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:233)
        at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:228)
        at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:226)
        at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:221)
        at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:92)
        at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:77)
        at org.sonar.batch.scan.ScanTask.scan(ScanTask.java:64)
        at org.sonar.batch.scan.ScanTask.execute(ScanTask.java:51)
        at org.sonar.batch.bootstrap.TaskContainer.doAfterStart(TaskContainer.java:125)
        at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:92)
        at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:77)
        at org.sonar.batch.bootstrap.BootstrapContainer.executeTask(BootstrapContainer.java:173)
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:95)
        at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
        at org.sonar.runner.batch.IsolatedLauncher.execute(IsolatedLauncher.java:48)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:87)
        ... 9 more
Caused by: org.sonar.api.utils.SonarException: java.nio.charset.MalformedInputException: Input length = 1
        at org.sonar.cxx.checks.FileRegularExpressionCheck.visitFile(FileRegularExpressionCheck.java:100)
        at com.sonar.sslr.impl.ast.AstWalker.walkAndVisit(AstWalker.java:67)
        at org.sonar.squidbridge.AstScanner.scanFiles(AstScanner.java:106)
        ... 36 more
Caused by: java.nio.charset.MalformedInputException: Input length = 1
        at java.nio.charset.CoderResult.throwException(CoderResult.java:277)
        at java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:798)
        at org.sonar.cxx.checks.FileRegularExpressionCheck.fromFile(FileRegularExpressionCheck.java:120)
        at org.sonar.cxx.checks.FileRegularExpressionCheck.visitFile(FileRegularExpressionCheck.java:95)
        ... 38 more
```

**Comment by guwirth** [comment]
Could you provide your settings of the FileRegularExpressionCheck rule please?
What is the setting of sonar.sourceEncoding?
What is the file encoding of the file some-header.h?

**Comment by guwirth** [comment]
@Bertk please Provider Input above to add Unit Test to the fix #373

**Comment by Bertk** [comment]
The encoding of the source file is most of the time *ANSI*. Only 2 files showing the issue have *UCS-2 Little Endian* encoding.  The *sonar.sourceEncoding* is not set and the regular expression is: *#include\s+"stdafx\.h"*
The files with ANSI encoding have some special characters: 
```
/*
Universitätsklinikum
 
Bühler
 
Copyright ©
*/
```
I hope this information is helpful.

**Comment by guwirth** [comment]
Which encoding has the file C:\TFS_Server\Server\some-folder\some-header.h?
Which operating system do you use?
Which language has the OS?

The rule is using the encoding to read the file and tries then to search for regular expression. The error occurs during decode which means conversion of file encoding to sonar.sourceEncoding fails/is not possible. 

What do you expect in such a case?
Is the patch working (means continue)?
To detect invalid file encodings there is the other new rule FileEncodingCheck.

**Comment by guwirth** [comment]
Looking here my understanding is:
* http://grepcode.com/file/repo1.maven.org/maven2/org.codehaus.sonar.sslr-squid-bridge/sslr-squid-bridge/2.2/com/sonar/sslr/squid/AstScanner.java?av=f
* http://grepcode.com/file/repo1.maven.org/maven2/org.codehaus.sonar.sslr-squid-bridge/sslr-squid-bridge/2.2/com/sonar/sslr/squid/checks/AbstractNamingCheck.java?av=f

1. init can check and throw exception
2. visitFile and visitNode should not throw an exception

Any other opinions?

**Comment by wenns** [comment]
To summarize the situation:
- sonar.sourceEncoding is not set, in which case it defaults to the system encoding
- the test project contains files, which cannot be read with this encoding. Consequently, the analysis breaks.

If this is the case (and It looks like), I would not consider this as a bug in the plugin. The only thing we can do here is to provide clear diagnostic info (point to the faulty file) and either break or continue with the analysis. I've a slighly preference for the latter.

And we do: the stack trace above includes the file name which cause the error.

And according to the above the fix is in this case to recode 'some-header'.

As for who may throw an exception: looking at the code in AstScanner it looks like an exception thrown either in init() or in visitor-methods would cancel the analysis. In the latter case the stack trace will contain the file name which caused this. As already said.

Im not even sure we should change the code. Maybe a try-catch around the actual decode and a message like " Cannot read file 'x' with encoding 'y' " passed into the SonarException.
