### ISSUE TITLE
The sslr-cxx-toolkit breaks when parsing some files

### ISSUE THREAD

**Issue by wenns** [wenns/sonar-cxx#374]
As soon as you give it something where the preprocessor is active e.g.:
```
#include <iostream>
...
```

it breaks with the following stake trace:

```
java.lang.NoSuchMethodError: org.slf4j.helpers.MessageFormatter.arrayFormat(Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String;
	at ch.qos.logback.classic.spi.LoggingEvent.getFormattedMessage(LoggingEvent.java:282)
	at ch.qos.logback.classic.pattern.MessageConverter.convert(MessageConverter.java:22)
	at ch.qos.logback.classic.pattern.MessageConverter.convert(MessageConverter.java:19)
	at ch.qos.logback.core.pattern.FormattingConverter.write(FormattingConverter.java:32)
	at ch.qos.logback.core.pattern.PatternLayoutBase.writeLoopOnConverters(PatternLayoutBase.java:110)
	at ch.qos.logback.classic.PatternLayout.doLayout(PatternLayout.java:132)
	at ch.qos.logback.classic.PatternLayout.doLayout(PatternLayout.java:51)
	at ch.qos.logback.core.WriterAppender.subAppend(WriterAppender.java:261)
	at ch.qos.logback.core.WriterAppender.append(WriterAppender.java:114)
	at ch.qos.logback.core.AppenderBase.doAppend(AppenderBase.java:87)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:60)
	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:439)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:393)
	at ch.qos.logback.classic.Logger.warn(Logger.java:722)
	at org.sonar.cxx.preprocessor.CxxPreprocessor.handleIncludeLine(CxxPreprocessor.java:499)
	at org.sonar.cxx.preprocessor.CxxPreprocessor.process(CxxPreprocessor.java:310)
	at com.sonar.sslr.impl.Lexer.preprocess(Lexer.java:159)
	at com.sonar.sslr.impl.Lexer.preprocess(Lexer.java:149)
	at com.sonar.sslr.impl.Lexer.lex(Lexer.java:138)
	at com.sonar.sslr.impl.Lexer.lex(Lexer.java:116)
	at com.sonar.sslr.impl.Parser.parse(Parser.java:77)
	at org.sonar.sslr.internal.toolkit.SourceCodeModel.setSourceCode(SourceCodeModel.java:62)
	at org.sonar.sslr.internal.toolkit.ToolkitPresenter.onSourceCodeParseButtonClick(ToolkitPresenter.java:123)
	at org.sonar.sslr.internal.toolkit.ToolkitViewImpl$5.actionPerformed(ToolkitViewImpl.java:203)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6516)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3311)
	at java.awt.Component.processEvent(Component.java:6281)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4872)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:708)
	at java.awt.EventQueue$4.run(EventQueue.java:706)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

It certainly has to do with this warning, which is printed at startup:
```
SLF4J: The requested version 1.5.6 by your slf4j binding is not compatible with [1.6]
SLF4J: See http://www.slf4j.org/codes.html#version_mismatch for further details.
```

**Comment by guwirth** [comment]
Still not sur if we should not update completely to 4.5.1 API?

**Comment by lcintrat** [comment]
A little more about this issue. Yesterday, I did not have log while running unit tests in Eclipse (Run as... -> JUnit). The message was http://www.slf4j.org/codes.html#StaticLoggerBinder.
I understand that no slf4j backend is available during testing. To resolve this issue, I added
```
<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-simple</artifactId>
    <version>1.7.9</version>
    <scope>test</scope>
</dependency>
```
At least, a backend should be added for test scope.
Hope this can help...

**Comment by lcintrat** [comment]
I tried with logback-classic, which is the binding used by the plugin.
In cxx-squid/pom.xml:

``` xml
<dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
      <scope>test</scope>
</dependency>
```

 But current version used by the plugin (0.9.15) seems to be incompatible with slf4j-api (1.6.2):

<code>
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/Ludovic/.m2/repository/ch/qos/logback/logback-classic/0.9.15/logback-classic-0.9.15.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/Ludovic/.m2/repository/org/slf4j/slf4j-jdk14/1.5.6/slf4j-jdk14-1.5.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: The requested version 1.5.6 by your slf4j binding is not compatible with [1.6]
SLF4J: See http://www.slf4j.org/codes.html#version_mismatch for further details.
</code>

If I change logback-classic version to 1.0.13 in cxx/pom.xml, all is good.

**Comment by wenns** [comment]
Thanks for the hints, they are helpful!
