### ISSUE TITLE
Missing sensor rule stops analysis

### ISSUE THREAD

**Issue by Bertk** [wenns/sonar-cxx#412]
SonarException is thrown if a rule does not exist in respository. This will stop the analysis and no issues will be loaded to SonarQube DB. In former C++ plug-in versions only a logging message with the details for the missing rules was created. 
-> Looks like exception handling in contextSaveViolation is not correct.
(SonarQube 4.5.2, JRE 8u31, Windows 7 SP1)

```
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
Total time: 23:02.890s
Final Memory: 50M/4315M
INFO: ------------------------------------------------------------------------
ERROR: Error during Sonar runner execution
org.sonar.runner.impl.RunnerException: Unable to execute Sonar
        at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:91)
        at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69)
        at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50)
        at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:102)
        at org.sonar.runner.api.Runner.execute(Runner.java:100)
        at org.sonar.runner.Main.executeTask(Main.java:70)
        at org.sonar.runner.Main.execute(Main.java:59)
        at org.sonar.runner.Main.main(Main.java:53)
Caused by: org.sonar.api.utils.SonarException: Cannot feed the data into sonar, details: 'The rule 'pclint:9152' does not exist.'
        at org.sonar.plugins.cxx.utils.CxxReportSensor.analyse(CxxReportSensor.java:129)
        at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:79)
        at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:70)
        at org.sonar.batch.phases.PhaseExecutor.execute(PhaseExecutor.java:119)
        at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:194)
        at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:92)
        at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:77)
        at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:233)
        at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:228)
        at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:226)
        at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:221)
        at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:92)
        at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:77)
        at org.sonar.batch.scan.ScanTask.scan(ScanTask.java:64)
        at org.sonar.batch.scan.ScanTask.execute(ScanTask.java:51)
        at org.sonar.batch.bootstrap.TaskContainer.doAfterStart(TaskContainer.java:125)
        at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:92)
        at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:77)
        at org.sonar.batch.bootstrap.BootstrapContainer.executeTask(BootstrapContainer.java:173)
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:95)
        at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
        at org.sonar.runner.batch.IsolatedLauncher.execute(IsolatedLauncher.java:48)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:87)
        ... 9 more
Caused by: The rule 'pclint:9152' does not exist.

```

**Comment by jmecosta** [comment]
This was what i mention earlier when there was the other discussion. But
thought it was handled by the changes introduced there...

**Comment by wenns** [comment]
Hints how to reproduce? What is the difference to the according scenario tested in importing_cppcheck_reports.feature, i.e:
```
  Scenario: The report mentions an unknown rule
     GIVEN the project "cppcheck_project"
     WHEN I run "sonar-runner -X -Dsonar.cxx.cppcheck.reportPath=rule_unknown.xml"
     THEN the analysis finishes successfully
         AND the server log (if locatable) contains no error/warning messages
         BUT the analysis log contains a line matching
              """
              .*ERROR.*Could not add the issue.*The rule '.*' does not exist.
              """
         AND the number of violations fed is 0
```

**Comment by Bertk** [comment]
I am not sure on the scenario but only the unknown rule shall be ignored and at the moment the analysis is stopped because the exception is not handled.

I modified **contextSaveViolation** and added *SonarException* logging. I checked this solution by inserting an issue which is not known into an existing report file. This was handled correctly with the modification of **contextSaveViolation**. 
```
12:14:19.386 ERROR - Could not add the issue, details: 'The rule 'pclint:9999' does not exist.'
12:14:19.558 INFO  - PC-Lint errors processed = 158
```
I think the 'org.sonar.api.utils.MessageException' should be replaced by 'org.sonar.api.utils.SonarException' in this context.
```
  private boolean contextSaveViolation(Resource resource, int lineNr, RuleKey rule, String msg) {
    Issuable issuable = perspectives.as(Issuable.class, resource);
    boolean result = false;
    if (issuable != null) {
      Issuable.IssueBuilder issueBuilder = issuable.newIssueBuilder()
          .ruleKey(rule)
          .message(msg);
      if (lineNr > 0) {
        issueBuilder = issueBuilder.line(lineNr);
      }
      Issue issue = issueBuilder.build();
      try{
        result = issuable.addIssue(issue);
      } catch (org.sonar.api.utils.MessageException me){
        CxxUtils.LOG.error("Could not add the issue, details: '{}'", me.toString());
      } catch (org.sonar.api.utils.SonarException mFail){
        CxxUtils.LOG.error("Could not add the issue, details: '{}'", mFail.toString());
      }
      if (result)
        violationsCount++;
    }
    return result;
  }
```

**Comment by Bertk** [comment]
The issue is already solved. The update of the C++ community plug-in was delayed.
