### ISSUE TITLE
Broken CI test scripts

### ISSUE THREAD

**Issue by guwirth** [wenns/sonar-cxx#415]
CI is no more running, getting:
```
The command "mvn test" exited with 0.
0.12s$ RAILS_ENV=production PATH=$PATH:/tmp/sonar-runner-2.4/bin SONARHOME=/tmp/sonarqube-4.5.1 behave
Exception SyntaxError: invalid syntax (environment.py, line 65)
Traceback (most recent call last):
File "/usr/local/bin/behave", line 11, in <module>
sys.exit(main())
File "/usr/local/lib/python2.7/dist-packages/behave/__main__.py", line 109, in main
failed = runner.run()
File "/usr/local/lib/python2.7/dist-packages/behave/runner.py", line 672, in run
return self.run_with_paths()
File "/usr/local/lib/python2.7/dist-packages/behave/runner.py", line 677, in run_with_paths
self.load_hooks()
File "/usr/local/lib/python2.7/dist-packages/behave/runner.py", line 631, in load_hooks
exec_file(hooks_path, self.hooks)
File "/usr/local/lib/python2.7/dist-packages/behave/runner.py", line 303, in exec_file
code = compile(f.read(), filename2, 'exec')
File "integration-tests/features/environment.py", line 65
print BRIGHT + "\nSetting up the test environment" + RESET_ALL
^
SyntaxError: invalid syntax
```

**Comment by wenns** [comment]
Ive fixed that. It still breaks in the openjdk7 environment, but for a different reason, which has to be fixed by the Travis guys, I suppose.
