### ISSUE TITLE
badly defined technical debt for cxx checks

### ISSUE THREAD

**Issue by jmecosta** [wenns/sonar-cxx#474]
Something is incorrect with this rule. get exception during analysis.

[15:37:08][Step 1/1] Caused by: java.lang.IllegalArgumentException: Rule 'cxx:CycleBetweenPackages' can not use 'Constant/issue' remediation function because this rule does not have a fixed remediation cost.
[15:37:08][Step 1/1] 	at org.sonar.batch.issue.ModuleIssues.calculateDebt(ModuleIssues.java:139)
[15:37:08][Step 1/1] 	at org.sonar.batch.issue.ModuleIssues.updateIssue(ModuleIssues.java:132)
[15:37:08][Step 1/1] 	at org.sonar.batch.issue.ModuleIssues.initAndAddIssue(ModuleIssues.java:100)
[15:37:08][Step 1/1] 	at org.sonar.batch.issue.DefaultIssuable.addIssue(DefaultIssuable.java:56)
[15:37:08][Step 1/1] 	at org.sonar.plugins.cxx.squid.DependencyAnalyzer.saveViolations(DependencyAnalyzer.java:225)
[15:37:08][Step 1/1] 	at org.sonar.plugins.cxx.squid.DependencyAnalyzer.save(DependencyAnalyzer.java:165)

**Comment by jmecosta** [comment]
sonarqube 5.1

**Comment by jmecosta** [comment]
seems related:
https://jira.codehaus.org/browse/SONARJAVA-433

**Comment by jmecosta** [comment]
after changing this rule to linear the analysis completed successfully. To be confirm from your side if this happens also

**Comment by guwirth** [comment]
> after changing this rule to linear the analysis completed successfully.

@jmecosta do you have a PR for this?

**Comment by jmecosta** [comment]
Nop, was waiting confirmation from some one else. Can do the PR if this is confirmed

**Comment by guwirth** [comment]
@Typz could you verify that please?

**Comment by jmecosta** [comment]
It should be enough to run a analysis with 5.1 that contains these kind of
issues

**Comment by jmecosta** [comment]
cant get this behaviour with latest snapshot... perhaps something with database. can be open if we run into this issue again

**Comment by chrissy25** [comment]
We are facing also the same issue during our analysis:
2015-05-19 09:16:39 ERROR: Error during Sonar runner execution
2015-05-19 09:16:39 ERROR: Unable to execute Sonar
2015-05-19 09:16:39 ERROR: Caused by: Rule 'cxx:CycleBetweenPackages' can not use 'Constant/issue' remediation function because this rule does not have a fixed remediation cost.

We are using:
- SonarQube 4.5.4 
- CXX 0.9.3

Do you already know a solution for this?

**Comment by jmecosta** [comment]
See the related issue, there is a link to the thread that contains the fix.
You should answer in that thread

**Comment by chrissy25** [comment]
do you mean this issue?
https://jira.codehaus.org/browse/SONARJAVA-433

Sorry but I am a little bit lost at the moment, do we have to configure something on our side, that it will work, and when yes, where do I do the configuration?

Thanks in advance for your help =)

**Comment by jmecosta** [comment]
This is the other issue
https://github.com/wenns/sonar-cxx/issues/437#issuecomment-103509169

Apparently for now you need to disable the rule
