### ISSUE TITLE
Execution failure with Sonar Version 5.0.1 

### ISSUE THREAD

**Issue by raja1985** [wenns/sonar-cxx#483]
Hi, I am getting below error during sonar execution: I have added the plugins list what i am using to build it.

![ravivarman mayilsamy thomsonreuters com_20150420_150039](https://cloud.githubusercontent.com/assets/4569281/7227499/c9b60fb6-e76e-11e4-8e68-e771db8baa5f.png)

INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
Total time: 12:14.283s
Final Memory: 31M/979M
INFO: ------------------------------------------------------------------------
ERROR: Error during Sonar runner execution
org.sonar.runner.impl.RunnerException: Unable to execute Sonar
        at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher
.java:91)
        at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69)
        at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50)
        at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:102
)
        at org.sonar.runner.api.Runner.execute(Runner.java:90)
        at org.sonar.runner.Main.executeTask(Main.java:70)
        at org.sonar.runner.Main.execute(Main.java:59)
        at org.sonar.runner.Main.main(Main.java:41)
Caused by: java.lang.IllegalArgumentException: Line must be null or greater than
 zero (got 0)
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java
:88)
        at org.sonar.api.issue.internal.DefaultIssue.setLine(DefaultIssue.java:2
63)
        at org.sonar.core.issue.DefaultIssueBuilder.build(DefaultIssueBuilder.ja
va:120)
        at org.sonar.core.issue.DefaultIssueBuilder.build(DefaultIssueBuilder.ja
va:33)
        at org.sonar.plugins.java.bridges.ChecksBridge.reportIssues(ChecksBridge
.java:68)
        at org.sonar.plugins.java.Bridges.reportIssues(Bridges.java:74)
        at org.sonar.plugins.java.Bridges.save(Bridges.java:61)
        at org.sonar.plugins.java.JavaSquidSensor.analyse(JavaSquidSensor.java:8
6)
        at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.
java:79)
        at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:7
0)
        at org.sonar.batch.phases.PhaseExecutor.execute(PhaseExecutor.java:122)
        at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanConta
iner.java:222)
        at org.sonar.api.platform.ComponentContainer.startComponents(ComponentCo
ntainer.java:93)
        at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.
java:78)
        at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.j
ava:235)
        at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScan
Container.java:230)
        at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanCon
tainer.java:223)
        at org.sonar.api.platform.ComponentContainer.startComponents(ComponentCo
ntainer.java:93)
        at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.
java:78)
        at org.sonar.batch.scan.ScanTask.scan(ScanTask.java:65)
        at org.sonar.batch.scan.ScanTask.execute(ScanTask.java:52)
        at org.sonar.batch.bootstrap.TaskContainer.doAfterStart(TaskContainer.ja
va:128)
        at org.sonar.api.platform.ComponentContainer.startComponents(ComponentCo
ntainer.java:93)
        at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.
java:78)
        at org.sonar.batch.bootstrap.BootstrapContainer.executeTask(BootstrapCon
tainer.java:171)
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:95)
        at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
        at org.sonar.runner.batch.IsolatedLauncher.execute(IsolatedLauncher.java
:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher
.java:87)
        ... 9 more

Thanks in advance!

**Comment by guwirth** [comment]
Can't see any C++ community plugin in your list?
Is this the right forum for your question?

**Comment by guwirth** [comment]
Close this. Please reopen if still a problem.
