### ISSUE TITLE
Can't start sslr-cxx-toolkit 0.9.3

### ISSUE THREAD

**Issue by guwirth** [wenns/sonar-cxx#486]
Can't start sslr-cxx-toolkit 0.9.3 on my machine. Can someone verify this please?

**Comment by guwirth** [comment]
see #493

**Comment by guwirth** [comment]
Starting the toolkit and pressing 'Parse Source Code' I get:
```
java.lang.NoClassDefFoundError: org/sonar/api/batch/fs/InputPath
	at org.sonar.cxx.toolkit.CxxConfigurationModel.getConfiguration(CxxConfigurationModel.java:87)
	at org.sonar.cxx.toolkit.CxxConfigurationModel.doGetParser(CxxConfigurationModel.java:72)
	at org.sonar.sslr.toolkit.AbstractConfigurationModel.ensureUpToDate(AbstractConfigurationModel.java:54)
	at org.sonar.sslr.toolkit.AbstractConfigurationModel.getParser(AbstractConfigurationModel.java:73)
	at org.sonar.sslr.internal.toolkit.SourceCodeModel.setSourceCode(SourceCodeModel.java:62)
	at org.sonar.sslr.internal.toolkit.ToolkitPresenter.onSourceCodeParseButtonClick(ToolkitPresenter.java:123)
	at org.sonar.sslr.internal.toolkit.ToolkitViewImpl$5.actionPerformed(ToolkitViewImpl.java:203)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
```
Someone an idea?

**Comment by jmecosta** [comment]
No idea, haven't tried to play with before

**Comment by guwirth** [comment]
Was a missing package include in POM, see 1384a2b
