### ISSUE TITLE
Issues with 0.9.2 and sonarqube 4.5.1

### ISSUE THREAD

**Issue by niharikard** [wenns/sonar-cxx#533]
I get this issues when usinh 0.9.2 CXX plugin and Sonar 4.5.1

ERROR web[o.a.c.c.C.[.[.[/]]  Exception sending context initialized event to listener instance of class org.sonar.server.platform.PlatformServletContextListener
org.sonar.api.utils.SonarException: XML is not valid
	at org.sonar.api.rules.XMLRuleParser.parse(XMLRuleParser.java:113) ~[sonar-deprecated-4.5.1.jar:na]
	at org.sonar.plugins.cxx.utils.CxxAbstractRuleRepository.createRules(CxxAbstractRuleRepository.java:75) ~[na:na]
	at org.sonar.server.rule.DeprecatedRulesDefinition.define(DeprecatedRulesDefinition.java:89) ~[sonar-server-4.5.1.jar:na]
	at org.sonar.server.rule.RuleDefinitionsLoader.load(RuleDefinitionsLoader.java:45) ~[sonar-server-4.5.1.jar:na]
	at org.sonar.server.rule.RegisterRules.start(RegisterRules.java:98) ~[sonar-server-4.5.1.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_45]
	at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.invokeMethod(ReflectionLifecycleStrategy.java:110) ~[picocontainer-2.14.3.jar:na]
	at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.start(ReflectionLifecycleStrategy.java:89) ~[picocontainer-2.14.3.jar:na]
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84) ~[picocontainer-2.14.3.jar:na]
	at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169) ~[picocontainer-2.14.3.jar:na]
	at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132) ~[picocontainer-2.14.3.jar:na]
	at org.picocontainer.behaviors.Stored.start(Stored.java:110) ~[picocontainer-2.14.3.jar:na]
	at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1015) ~[picocontainer-2.14.3.jar:na]
	at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1008) ~[picocontainer-2.14.3.jar:na]
	at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:766) ~[picocontainer-2.14.3.jar:na]
	at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:91) ~[sonar-plugin-api-4.5.1.jar:na]
	at org.sonar.server.platform.ServerComponents$1.doPrivileged(ServerComponents.java:590) ~[sonar-server-4.5.1.jar:na]
	at org.sonar.server.user.DoPrivileged.execute(DoPrivileged.java:43) ~[sonar-server-4.5.1.jar:na]
	at org.sonar.server.platform.ServerComponents.executeStartupTasks(ServerComponents.java:586) ~[sonar-server-4.5.1.jar:na]
	at org.sonar.server.platform.Platform.executeStartupTasks(Platform.java:126) ~[sonar-server-4.5.1.jar:na]
	at org.sonar.server.platform.Platform.startLevel34Containers(Platform.java:122) ~[sonar-server-4.5.1.jar:na]
	at org.sonar.server.platform.Platform.doStart(Platform.java:81) ~[sonar-server-4.5.1.jar:na]
	at org.sonar.server.platform.PlatformServletContextListener.contextInitialized(PlatformServletContextListener.java:43) ~[sonar-server-4.5.1.jar:na]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4973) [tomcat-embed-core-7.0.54.jar:7.0.54]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5467) [tomcat-embed-core-7.0.54.jar:7.0.54]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-7.0.54.jar:7.0.54]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559) [tomcat-embed-core-7.0.54.jar:7.0.54]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549) [tomcat-embed-core-7.0.54.jar:7.0.54]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_45]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_45]
Caused by: com.ctc.wstx.exc.WstxUnexpectedCharException: Unexpected character '-' (code 45) in prolog; expected '<'
 at [row,col {unknown-source}]: [4,1]
	at com.ctc.wstx.sr.StreamScanner.throwUnexpectedChar(StreamScanner.java:639) ~[woodstox-core-lgpl-4.2.0.jar:4.2.0]
	at com.ctc.wstx.sr.BasicStreamReader.nextFromProlog(BasicStreamReader.java:2052) ~[woodstox-core-lgpl-4.2.0.jar:4.2.0]
	at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1134) ~[woodstox-core-lgpl-4.2.0.jar:4.2.0]
	at org.codehaus.staxmate.in.SMHierarchicCursor.getNext(SMHierarchicCursor.java:71) ~[staxmate-2.0.1.jar:na]
	at org.codehaus.staxmate.in.SMInputCursor.advance(SMInputCursor.java:1631) ~[staxmate-2.0.1.jar:na]
	at org.sonar.api.rules.XMLRuleParser.parse(XMLRuleParser.java:99) ~[sonar-deprecated-4.5.1.jar:na]
	... 34 common frames omitted
2015.06.16 13:42:08 INFO  web[jruby.rack]  jruby 1.7.9 (ruby-1.8.7p370) 2013-12-06 87b108a on Java HotSpot(TM) 64-Bit Server VM 1.8.0_45-b14 +indy [Windows Server 2008 R2-amd64]
2015.06.16 13:42:08 INFO  web[jruby.rack]  using a shared (threadsafe!) runtime.

Can somebody help me understand, what is wrong. As per documentation, the versions seem to be compatible for plugin and sonar.

Same is the issue with Cxx 0.9.1 as well.

Please suggest

**Comment by jmecosta** [comment]
Try with 0.9.4

**Comment by niharikard** [comment]
9.4 is not compatible with 4.5.1. please suggest which is the compatible version for sonar 4.5.1, none of the plugin versions seem to be working.

**Comment by jmecosta** [comment]
unless you manage to delete the xml file from database i think you need to
upgrade to 4.5.4 wich is the last LTS. then you can use 0.9.3 or 0.9.4. if
this is not possible than the only suggestion is for  you to build from
sources and comment external import of rules so you can go to the web ui
and delete the invalid xml entry.

**Comment by guwirth** [comment]
I close it. Agree with @jmecosta
