### ISSUE TITLE
ReservedNamesCheck exception #define _ ...

### ISSUE THREAD

**Issue by rlucca** [wenns/sonar-cxx#543]
Hi there,

The new plugin is throwing exception when I make a alias to a field in a struct named as "_".
[code]
#undef _
#define _ ks._
[/code]

The exception threw:
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 1
	at java.lang.String.charAt(String.java:658)
	at org.sonar.cxx.checks.ReservedNamesCheck.visitFile(ReservedNamesCheck.java:73)
	at com.sonar.sslr.impl.ast.AstWalker.walkAndVisit(AstWalker.java:67)
	at org.sonar.squidbridge.AstScanner.scanFiles(AstScanner.java:106)
	... 35 more

**Comment by guwirth** [comment]
> The new plugin is throwing exception 
Which version? 0.9.3 or 0.9.4-RC1?

Could you also provide C++ code snippet/example please.
```C++
#undef _
#define _ ks.
```

**Comment by guwirth** [comment]
Oh there is already a PR (saw it too late).
